package render

// tagNames maps MARC21 bibliographic tags to their official field labels.
// Only the fields that actually turn up in library catalogue records are
// listed; anything missing renders with its bare tag, which is the right
// behaviour for local fields (9XX) anyway.
var tagNames = map[string]string{
	"001": "Control Number",
	"003": "Control Number Identifier",
	"005": "Date and Time of Latest Transaction",
	"006": "Fixed-Length Data Elements - Additional",
	"007": "Physical Description Fixed Field",
	"008": "Fixed-Length Data Elements",
	"010": "Library of Congress Control Number",
	"013": "Patent Control Information",
	"015": "National Bibliography Number",
	"016": "National Bibliographic Agency Control Number",
	"017": "Copyright Registration Number",
	"018": "Copyright Article-Fee Code",
	"020": "International Standard Book Number",
	"022": "International Standard Serial Number",
	"024": "Other Standard Identifier",
	"025": "Overseas Acquisition Number",
	"026": "Fingerprint Identifier",
	"027": "Standard Technical Report Number",
	"028": "Publisher or Distributor Number",
	"030": "CODEN Designation",
	"033": "Date/Time and Place of an Event",
	"034": "Coded Cartographic Mathematical Data",
	"035": "System Control Number",
	"037": "Source of Acquisition",
	"040": "Cataloging Source",
	"041": "Language Code",
	"042": "Authentication Code",
	"043": "Geographic Area Code",
	"044": "Country of Publishing Producing Entity Code",
	"045": "Time Period of Content",
	"046": "Special Coded Dates",
	"047": "Form of Musical Composition Code",
	"048": "Number of Musical Instruments or Voices Code",
	"050": "Library of Congress Call Number",
	"052": "Geographic Classification",
	"060": "National Library of Medicine Call Number",
	"072": "Subject Category Code",
	"080": "Universal Decimal Classification Number",
	"082": "Dewey Decimal Classification Number",
	"084": "Other Classification Number",
	"085": "Synthesized Classification Number Components",
	"086": "Government Document Classification Number",
	"088": "Report Number",
	"100": "Main Entry - Personal Name",
	"110": "Main Entry - Corporate Name",
	"111": "Main Entry - Meeting Name",
	"130": "Main Entry - Uniform Title",
	"210": "Abbreviated Title",
	"222": "Key Title",
	"240": "Uniform Title",
	"242": "Translation of Title by Cataloging Agency",
	"243": "Collective Uniform Title",
	"245": "Title Statement",
	"246": "Varying Form of Title",
	"247": "Former Title",
	"250": "Edition Statement",
	"254": "Musical Presentation Statement",
	"255": "Cartographic Mathematical Data",
	"256": "Computer File Characteristics",
	"257": "Country of Producing Entity",
	"260": "Publication, Distribution, etc. (Imprint)",
	"263": "Projected Publication Date",
	"264": "Production, Publication, Distribution, Manufacture",
	"270": "Address",
	"300": "Physical Description",
	"306": "Playing Time",
	"310": "Current Publication Frequency",
	"321": "Former Publication Frequency",
	"336": "Content Type",
	"337": "Media Type",
	"338": "Carrier Type",
	"340": "Physical Medium",
	"344": "Sound Characteristics",
	"347": "Digital File Characteristics",
	"348": "Notated Music Characteristics",
	"351": "Organization and Arrangement of Materials",
	"362": "Dates of Publication and/or Sequential Designation",
	"363": "Normalized Date and Sequential Designation",
	"365": "Trade Price",
	"380": "Form of Work",
	"382": "Medium of Performance",
	"385": "Audience Characteristics",
	"386": "Creator/Contributor Characteristics",
	"388": "Time Period of Creation",
	"490": "Series Statement",
	"500": "General Note",
	"501": "With Note",
	"502": "Dissertation Note",
	"504": "Bibliography, etc. Note",
	"505": "Formatted Contents Note",
	"506": "Restrictions on Access Note",
	"508": "Creation/Production Credits Note",
	"510": "Citation/References Note",
	"511": "Participant or Performer Note",
	"513": "Type of Report and Period Covered Note",
	"515": "Numbering Peculiarities Note",
	"516": "Type of Computer File or Data Note",
	"518": "Date/Time and Place of an Event Note",
	"520": "Summary, etc.",
	"521": "Target Audience Note",
	"524": "Preferred Citation of Described Materials Note",
	"525": "Supplement Note",
	"526": "Study Program Information Note",
	"530": "Additional Physical Form Available Note",
	"533": "Reproduction Note",
	"534": "Original Version Note",
	"535": "Location of Originals/Duplicates Note",
	"536": "Funding Information Note",
	"538": "System Details Note",
	"540": "Terms Governing Use and Reproduction Note",
	"541": "Immediate Source of Acquisition Note",
	"542": "Information Relating to Copyright Status",
	"544": "Location of Other Archival Materials Note",
	"545": "Biographical or Historical Data",
	"546": "Language Note",
	"547": "Former Title Complexity Note",
	"550": "Issuing Body Note",
	"555": "Cumulative Index/Finding Aids Note",
	"556": "Information About Documentation Note",
	"561": "Ownership and Custodial History",
	"562": "Copy and Version Identification Note",
	"563": "Binding Information",
	"580": "Linking Entry Complexity Note",
	"581": "Publications About Described Materials Note",
	"583": "Action Note",
	"585": "Exhibitions Note",
	"586": "Awards Note",
	"588": "Source of Description Note",
	"590": "Local Note",
	"600": "Subject Added Entry - Personal Name",
	"610": "Subject Added Entry - Corporate Name",
	"611": "Subject Added Entry - Meeting Name",
	"630": "Subject Added Entry - Uniform Title",
	"647": "Subject Added Entry - Named Event",
	"648": "Subject Added Entry - Chronological Term",
	"650": "Subject Added Entry - Topical Term",
	"651": "Subject Added Entry - Geographic Name",
	"653": "Index Term - Uncontrolled",
	"654": "Subject Added Entry - Faceted Topical Terms",
	"655": "Index Term - Genre/Form",
	"656": "Index Term - Occupation",
	"657": "Index Term - Function",
	"658": "Index Term - Curriculum Objective",
	"662": "Subject Added Entry - Hierarchical Place Name",
	"700": "Added Entry - Personal Name",
	"710": "Added Entry - Corporate Name",
	"711": "Added Entry - Meeting Name",
	"720": "Added Entry - Uncontrolled Name",
	"730": "Added Entry - Uniform Title",
	"740": "Added Entry - Uncontrolled Related/Analytical Title",
	"751": "Added Entry - Geographic Name",
	"752": "Added Entry - Hierarchical Place Name",
	"753": "System Details Access to Computer Files",
	"758": "Resource Identifier",
	"760": "Main Series Entry",
	"762": "Subseries Entry",
	"765": "Original Language Entry",
	"767": "Translation Entry",
	"770": "Supplement/Special Issue Entry",
	"772": "Supplement Parent Entry",
	"773": "Host Item Entry",
	"774": "Constituent Unit Entry",
	"775": "Other Edition Entry",
	"776": "Additional Physical Form Entry",
	"777": "Issued With Entry",
	"780": "Preceding Entry",
	"785": "Succeeding Entry",
	"786": "Data Source Entry",
	"787": "Other Relationship Entry",
	"800": "Series Added Entry - Personal Name",
	"810": "Series Added Entry - Corporate Name",
	"811": "Series Added Entry - Meeting Name",
	"830": "Series Added Entry - Uniform Title",
	"850": "Holding Institution",
	"852": "Location",
	"856": "Electronic Location and Access",
	"880": "Alternate Graphic Representation",
	"882": "Replacement Record Information",
	"883": "Metadata Provenance",
	"884": "Description Conversion Information",
	"885": "Matching Information",
	"887": "Non-MARC Information Field",
}

// TagName returns the MARC21 label for tag, or "" when the tag is local or
// unregistered.
func TagName(tag string) string { return tagNames[tag] }
